### ISSUE TITLE
About the security: is it safe to store API key in localStorage?

### ISSUE THREAD

**Issue by EazycTee** [ztjhz/BetterChatGPT#147]
I realized that the API key is stored in browser's localStorage. Though we use HTTPS to request the API, bug I wonder whether the browser's extensions have the ability to access localStorage...
Nevertheless, this repo is great:)

**Comment by lindebuyer** [comment]
Same concern. Some basic encryption would be nice

**Comment by ayaka14732** [comment]
Thank you for raising your concern about the storage of API keys in the browser's localStorage. We understand the importance of data security and would like to clarify that this is a deliberate choice made by the development team.

Firstly, it is generally safe to store sensitive data such as API keys in localStorage, which is similar to how login credentials are stored as cookies. While browser extensions may have access to localStorage, it is unlikely that a malicious software with access to localStorage will know what the API key is for or which website it belongs to.

That being said, we acknowledge that if a malicious software is specifically targeting OpenAI's API key, they will always be able to obtain the key since the encryption scheme is public. Furthermore, there is no other place to store the key for encryption other than localStorage. If a malicious software has access to localStorage, they can also access the key for encryption.

As a responsible developer, we should not give users a false sense of safety, even if the API key is encrypted. We strongly advise users not to install untrusted browser extensions, regardless of whether the key is encrypted or not.

Thank you for bringing up your concerns, and please do not hesitate to reach out if you have any further questions or suggestions.

**Comment by EazycTee** [comment]
Thanks for the reply:)

**Comment by lp123sun** [comment]
> Thank you for raising your concern about the storage of API keys in the browser's localStorage. We understand the importance of data security and would like to clarify that this is a deliberate choice made by the development team.感谢您关注浏览器本地存储中 API 密钥的存储问题。我们理解数据安全的重要性，在此澄清这是开发团队深思熟虑的选择。
> 
> Firstly, it is generally safe to store sensitive data such as API keys in localStorage, which is similar to how login credentials are stored as cookies. While browser extensions may have access to localStorage, it is unlikely that a malicious software with access to localStorage will know what the API key is for or which website it belongs to.首先，将 API 密钥等敏感数据存储在 localStorage 中通常是安全的，这类似于将登录凭据存储为 cookie 的方式。虽然浏览器扩展程序可以访问 localStorage，但可以访问 localStorage 的恶意软件不太可能知道 API 密钥的用途或它属于哪个网站。
> 
> That being said, we acknowledge that if a malicious software is specifically targeting OpenAI's API key, they will always be able to obtain the key since the encryption scheme is public. Furthermore, there is no other place to store the key for encryption other than localStorage. If a malicious software has access to localStorage, they can also access the key for encryption.话虽如此，我们承认，如果恶意软件专门针对 OpenAI 的 API 密钥，他们将始终能够获得密钥，因为加密方案是公开的。此外，除了 localStorage 之外，没有其他地方可以存储加密密钥。如果恶意软件可以访问 localStorage，他们也可以访问密钥进行加密。
> 
> As a responsible developer, we should not give users a false sense of safety, even if the API key is encrypted. We strongly advise users not to install untrusted browser extensions, regardless of whether the key is encrypted or not.作为一个负责任的开发者，我们不应该给用户一种错误的安全感，即使 API 密钥是加密的。我们强烈建议用户不要安装不受信任的浏览器扩展，无论密钥是否加密。
> 
> Thank you for bringing up your concerns, and please do not hesitate to reach out if you have any further questions or suggestions.感谢您提出疑虑，如果您有任何进一步的问题或建议，请随时与我们联系。

我在自己的vps上面部署，vps页面设置了密码访问，怎么样把自己申请的openai api key放在vps上面呢？

**Comment by ztjhz** [comment]
可以放在 .env

**Comment by solidarity-forever** [comment]
> 可以放在 .env

请问如果把这一工程打包为纯静态页面放在nginx上运行而不是直接使用nodejs启动，这个文件中的配置会生效吗

**Comment by solidarity-forever** [comment]
> > 可以放在 .env
> 
> 请问如果把这一工程打包为纯静态页面放在nginx上运行而不是直接使用nodejs启动，这个文件中的配置会生效吗

ok 亲测生效
