### ISSUE TITLE
Consider to better index folder property of chat interface

### ISSUE THREAD

**Issue by tnga** [ztjhz/BetterChatGPT#175]
https://github.com/ztjhz/BetterChatGPT/blob/main/src/types/chat.ts#:~:text=title%3A%20string%3B-,folder%3F%3A%20string%3B,-messages%3A%20MessageInterface%5B%5D%3B

The use of a non-changing property for indexing is generally recommended. 
For example, folder names can be changed as desired by the user. 
While the code handles the change well by updating the folder name across all associated chats, this approach adds maintenance overhead that may not be necessary if another identifier such as UUID, shortID, nanoID, or ID were used instead.
#

**Comment by ztjhz** [comment]
Thank you for the suggestion! This is something that we are definitely going to implement in the future. The original intention of using the folder name for each chat is so that when the chats are imported, the folders are imported as well. This was a temporary workaround for adding folders imports while not changing the `import/export` function. In the future, we do plan to change the `import/export` function to include folders, so that the individual chats can use UUID instead of folder names.

**Comment by ztjhz** [comment]
@tnga I have improved it in #188
