### ISSUE TITLE
Enter and Shift+Enter behavior do not match ChatGPT

### ISSUE THREAD

**Issue by jackschedel** [ztjhz/BetterChatGPT#255]
Enter to Submit Enabled (default):
 - new message: enter=submits, shift+enter = new line
 - editing message: shift+enter=submit, enter= new line

Enter to Submit Disabled:
 - new message: shift+enter=submit, enter= new line
 - editing message: shift+enter=submit, enter= new line

ChatGPT:
 - new message: enter=submits, shift+enter = new line
 - editing message: shift+enter=new line, enter= new line

**this is incredibly inconsistent. I would like to see the default setting ChatGPT's behavior, and Enter to Submit Disabled:**
 - new message: enter=new line, shift+enter = new line
 - editing message: shift+enter=new line, enter= new line

**Comment by ztjhz** [comment]
The aim of BetterChatGPT is not to simply replicate ChatGPT's functionality, including style (e.g. padding) and submission logic. Rather, our objective is to enhance the user experience by introducing new features, buttons, and UI enhancements not found on the original ChatGPT website. This would make BetterChatGPT "inconsistent" with the original ChatGPT website.

While new messages will continue to follow ChatGPT's existing process, we believe that editing messages should be improved by allowing users to save their changes with a simple `shift+enter` keystroke. This will save users the trouble of having to manually click the `save` button. This provides more flexibility, convenience and efficiency which can enhance the user experience.

**Comment by jackschedel** [comment]
I personally find myself shift+enter submitting quite often when editing, but if this is your ideal behavior, I'll just change this on my personal mirror instead.

**Comment by jackschedel** [comment]
changed here:

https://github.com/jackschedel/gpt.koaladev.io/commit/43c2bd65fe8ab53edf20b95687b62be80b108e2a

**Comment by ztjhz** [comment]
Got it 👍

I thought the original ChatGPT shift+enter is newline when editing.

**Comment by zhangt2333** [comment]
It is glad that someone has already mentioned this issue. When I first began using BetterChatGPT, I changed the default shortcut for submitting requests from `Shift+Enter` to `Enter` (In most of the IM software and editors, I use `Shift+Enter` for line breaks).

I am wondering why the behavior of the message editing box remains unchanged even after enabling the `Enter to Submit` feature. 

### Current Behavior 

<table border="1">
  <tr>
    <td rowspan="2">Edit Box</td>
    <td colspan="2">'Enter to Submit' Disabled</td>
    <td colspan="2">'Enter to Submit' Enabled</td>
  </tr>
  <tr>
    <td>Enter</td>
    <td>Shift+Enter</td>
    <td>Enter</td>
    <td>Shift+Enter</td>
  </tr>
  <tr>
    <td>new message</td>
    <td>new line</td>
    <td>save & submit</td>
    <td>save & submit</td>
    <td>new line</td>
  </tr>
  <tr>
    <td>editing message</td>
    <td>new line</td>
    <td>save</td>
    <td>new line</td>
    <td>save</td>
  </tr>
</table>

### Expected Behavior 

<table border="1">
  <tr>
    <td rowspan="2">Edit Box</td>
    <td colspan="2">'Enter to Submit' Disabled</td>
    <td colspan="2">'Enter to Submit' Enabled</td>
  </tr>
  <tr>
    <td>Enter</td>
    <td>Shift+Enter</td>
    <td>Enter</td>
    <td>Shift+Enter</td>
  </tr>
  <tr>
    <td>new message</td>
    <td>new line</td>
    <td>save & submit</td>
    <td>save & submit</td>
    <td>new line</td>
  </tr>
  <tr>
    <td>editing message</td>
    <td>new line</td>
    <td>save</td>
    <td><strong>save</strong></td>
    <td><strong>new line</strong></td>
  </tr>
</table>

### Suggested Solution

* Introduce breaking changes: make option `Enter to Submit` be abled to change the behavior of the message editing box
* DO NOT introduce breaking changes: add annother option `Shift+Enter to New Line` to accommodate those who prefer to use Shift + Enter for line breaks.

**Comment by ztjhz** [comment]
I will fix this :+1:
