### ISSUE TITLE
api of http protocol can't work on BetterChatGPT

### ISSUE THREAD

**Issue by Geniucker** [ztjhz/BetterChatGPT#315]
The locally deployed API using the HTTP protocol seems to be unusable because the website is using HTTPS and cannot load HTTP resources.

**Comment by ayaka14732** [comment]
If the locally deployed API is inaccessible due to the website using HTTPS and not loading HTTP resources, you can try modifying your browser settings to allow mixed content. Here's a step-by-step guide for some popular browsers:

1. Google Chrome:
   - Click on the padlock icon in the address bar (left side).
   - In the dropdown menu, click "Site settings."
   - Scroll down to the "Insecure content" section.
   - Select "Allow" or "Allow all" to enable loading of mixed content.

2. Mozilla Firefox:
   - Click on the padlock icon in the address bar (left side).
   - In the dropdown menu, click the right arrow (">") next to the connection information.
   - Click "Disable protection for now" to temporarily allow mixed content.

3. Microsoft Edge:
   - Click on the padlock icon in the address bar (left side).
   - In the dropdown menu, click "Site permissions."
   - Under the "Insecure content" section, select "Allow" to enable loading of mixed content.

Please note that allowing mixed content can potentially compromise the security of the website you are visiting. It is recommended to use this setting only for testing or development purposes and revert it back to the default setting afterward.

Alternatively, if possible, consider deploying your API with HTTPS to ensure compatibility with modern web standards and improve security.
