### ISSUE TITLE
Clarification on Input/Output Length Parameters for gpt-4-1106-preview and gpt-4-0125-preview Models

### ISSUE THREAD

**Issue by MBaltz** [ztjhz/BetterChatGPT#533]
I'm not sure if the guide and the actual code match up, especially about how much data the gpt-4-**1106**-preview and gpt-4-**0125**-preview models can handle. The guide says both models can deal with the same amount of data at once. But, looking at the code, it seems there's a difference in their settings.

https://github.com/ztjhz/BetterChatGPT/blob/ecad41fd729cb36968aa4866391692d02a51af89/src/constants/chat.ts#L50-L51

---
#### Version / Description / Context
_gpt-4-**0125**-preview_
_Description:_ The latest GPT-4 model intended to reduce cases of “laziness” where the model doesn’t complete a task. Returns a maximum of 4,096 output tokens. 
_Context window:_ 128,000 tokens

_gpt-4-**1106**-preview_
_Description:_ GPT-4 Turbo model featuring improved instruction following, JSON mode, reproducible outputs, parallel function calling, and more. Returns a maximum of 4,096 output tokens. This preview model is not yet suited for production traffic.
_Context window:_ 128,000 tokens

_Reference:_
https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo

**Comment by MBaltz** [comment]
This PR approach that:
https://github.com/ztjhz/BetterChatGPT/pull/525

**Comment by kaz-on** [comment]
I'm interested in this issue.

This value seems to have been discussed in #521.
And I encountered the same problem as @almagest21's comment (https://github.com/ztjhz/BetterChatGPT/pull/521#issuecomment-1925471757) regarding "Max Token" when using gpt-4-0125-preview.

It appears there's confusion due to a discrepancy between what "Max Token" is described as and how it's actually utilized.

"Max Token" is described in this application as "The maximum number of tokens to generate in the chat completion."
https://github.com/ztjhz/BetterChatGPT/blob/ecad41fd729cb36968aa4866391692d02a51af89/public/locales/en/model.json#L5-L6

However, in practice, the `max_tokens` parameter in the API calls is set to `undefined` here:
https://github.com/ztjhz/BetterChatGPT/blob/ecad41fd729cb36968aa4866391692d02a51af89/src/api/api.ts#L52
and here:
https://github.com/ztjhz/BetterChatGPT/blob/ecad41fd729cb36968aa4866391692d02a51af89/src/api/api.ts#L105

Instead, "Max Token" is utilized as a parameter for `limitMessageTokens` function, which is meant to limit the number of input tokens.
https://github.com/ztjhz/BetterChatGPT/blob/ecad41fd729cb36968aa4866391692d02a51af89/src/hooks/useSubmit.ts#L73-L77

So `modelMaxToken` needs to be set to the value in the Context Window and should be 128000 in gpt-4-0125-preview.
I think the proper approach is to match the description with the actual behavior, but it is not clear to me which is correct, the description or the behavior.
